// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chatservice.proto

package chatservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUserResponse struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateChatRoomRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatRoomName         string   `protobuf:"bytes,2,opt,name=chatRoomName,proto3" json:"chatRoomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatRoomRequest) Reset()         { *m = CreateChatRoomRequest{} }
func (m *CreateChatRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateChatRoomRequest) ProtoMessage()    {}
func (*CreateChatRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{4}
}

func (m *CreateChatRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatRoomRequest.Unmarshal(m, b)
}
func (m *CreateChatRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateChatRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatRoomRequest.Merge(m, src)
}
func (m *CreateChatRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateChatRoomRequest.Size(m)
}
func (m *CreateChatRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatRoomRequest proto.InternalMessageInfo

func (m *CreateChatRoomRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateChatRoomRequest) GetChatRoomName() string {
	if m != nil {
		return m.ChatRoomName
	}
	return ""
}

type CreateChatRoomResponse struct {
	ChatRoomID           int64    `protobuf:"varint,1,opt,name=chatRoomID,proto3" json:"chatRoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChatRoomResponse) Reset()         { *m = CreateChatRoomResponse{} }
func (m *CreateChatRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateChatRoomResponse) ProtoMessage()    {}
func (*CreateChatRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{5}
}

func (m *CreateChatRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChatRoomResponse.Unmarshal(m, b)
}
func (m *CreateChatRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChatRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateChatRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChatRoomResponse.Merge(m, src)
}
func (m *CreateChatRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateChatRoomResponse.Size(m)
}
func (m *CreateChatRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChatRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChatRoomResponse proto.InternalMessageInfo

func (m *CreateChatRoomResponse) GetChatRoomID() int64 {
	if m != nil {
		return m.ChatRoomID
	}
	return 0
}

type ListChatRoomsRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListChatRoomsRequest) Reset()         { *m = ListChatRoomsRequest{} }
func (m *ListChatRoomsRequest) String() string { return proto.CompactTextString(m) }
func (*ListChatRoomsRequest) ProtoMessage()    {}
func (*ListChatRoomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{6}
}

func (m *ListChatRoomsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChatRoomsRequest.Unmarshal(m, b)
}
func (m *ListChatRoomsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChatRoomsRequest.Marshal(b, m, deterministic)
}
func (m *ListChatRoomsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChatRoomsRequest.Merge(m, src)
}
func (m *ListChatRoomsRequest) XXX_Size() int {
	return xxx_messageInfo_ListChatRoomsRequest.Size(m)
}
func (m *ListChatRoomsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChatRoomsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListChatRoomsRequest proto.InternalMessageInfo

func (m *ListChatRoomsRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type ListChatRoomsResponse struct {
	Chatrooms            []*ListChatRoom `protobuf:"bytes,1,rep,name=chatrooms,proto3" json:"chatrooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListChatRoomsResponse) Reset()         { *m = ListChatRoomsResponse{} }
func (m *ListChatRoomsResponse) String() string { return proto.CompactTextString(m) }
func (*ListChatRoomsResponse) ProtoMessage()    {}
func (*ListChatRoomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{7}
}

func (m *ListChatRoomsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChatRoomsResponse.Unmarshal(m, b)
}
func (m *ListChatRoomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChatRoomsResponse.Marshal(b, m, deterministic)
}
func (m *ListChatRoomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChatRoomsResponse.Merge(m, src)
}
func (m *ListChatRoomsResponse) XXX_Size() int {
	return xxx_messageInfo_ListChatRoomsResponse.Size(m)
}
func (m *ListChatRoomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChatRoomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListChatRoomsResponse proto.InternalMessageInfo

func (m *ListChatRoomsResponse) GetChatrooms() []*ListChatRoom {
	if m != nil {
		return m.Chatrooms
	}
	return nil
}

type ListChatRoom struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListChatRoom) Reset()         { *m = ListChatRoom{} }
func (m *ListChatRoom) String() string { return proto.CompactTextString(m) }
func (*ListChatRoom) ProtoMessage()    {}
func (*ListChatRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{8}
}

func (m *ListChatRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChatRoom.Unmarshal(m, b)
}
func (m *ListChatRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChatRoom.Marshal(b, m, deterministic)
}
func (m *ListChatRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChatRoom.Merge(m, src)
}
func (m *ListChatRoom) XXX_Size() int {
	return xxx_messageInfo_ListChatRoom.Size(m)
}
func (m *ListChatRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChatRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ListChatRoom proto.InternalMessageInfo

func (m *ListChatRoom) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListChatRoom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinChatRoomRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatRoomID           int64    `protobuf:"varint,2,opt,name=chatRoomID,proto3" json:"chatRoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinChatRoomRequest) Reset()         { *m = JoinChatRoomRequest{} }
func (m *JoinChatRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinChatRoomRequest) ProtoMessage()    {}
func (*JoinChatRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{9}
}

func (m *JoinChatRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinChatRoomRequest.Unmarshal(m, b)
}
func (m *JoinChatRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinChatRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinChatRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinChatRoomRequest.Merge(m, src)
}
func (m *JoinChatRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinChatRoomRequest.Size(m)
}
func (m *JoinChatRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinChatRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinChatRoomRequest proto.InternalMessageInfo

func (m *JoinChatRoomRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *JoinChatRoomRequest) GetChatRoomID() int64 {
	if m != nil {
		return m.ChatRoomID
	}
	return 0
}

type JoinChatRoomResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinChatRoomResponse) Reset()         { *m = JoinChatRoomResponse{} }
func (m *JoinChatRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinChatRoomResponse) ProtoMessage()    {}
func (*JoinChatRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{10}
}

func (m *JoinChatRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinChatRoomResponse.Unmarshal(m, b)
}
func (m *JoinChatRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinChatRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinChatRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinChatRoomResponse.Merge(m, src)
}
func (m *JoinChatRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinChatRoomResponse.Size(m)
}
func (m *JoinChatRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinChatRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinChatRoomResponse proto.InternalMessageInfo

type LeaveChatRoomRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatRoomID           int64    `protobuf:"varint,2,opt,name=chatRoomID,proto3" json:"chatRoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveChatRoomRequest) Reset()         { *m = LeaveChatRoomRequest{} }
func (m *LeaveChatRoomRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveChatRoomRequest) ProtoMessage()    {}
func (*LeaveChatRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{11}
}

func (m *LeaveChatRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveChatRoomRequest.Unmarshal(m, b)
}
func (m *LeaveChatRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveChatRoomRequest.Marshal(b, m, deterministic)
}
func (m *LeaveChatRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveChatRoomRequest.Merge(m, src)
}
func (m *LeaveChatRoomRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveChatRoomRequest.Size(m)
}
func (m *LeaveChatRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveChatRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveChatRoomRequest proto.InternalMessageInfo

func (m *LeaveChatRoomRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LeaveChatRoomRequest) GetChatRoomID() int64 {
	if m != nil {
		return m.ChatRoomID
	}
	return 0
}

type LeaveChatRoomResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveChatRoomResponse) Reset()         { *m = LeaveChatRoomResponse{} }
func (m *LeaveChatRoomResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveChatRoomResponse) ProtoMessage()    {}
func (*LeaveChatRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{12}
}

func (m *LeaveChatRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveChatRoomResponse.Unmarshal(m, b)
}
func (m *LeaveChatRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveChatRoomResponse.Marshal(b, m, deterministic)
}
func (m *LeaveChatRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveChatRoomResponse.Merge(m, src)
}
func (m *LeaveChatRoomResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveChatRoomResponse.Size(m)
}
func (m *LeaveChatRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveChatRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveChatRoomResponse proto.InternalMessageInfo

type SendMessageRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatRoomID           int64    `protobuf:"varint,2,opt,name=chatRoomID,proto3" json:"chatRoomID,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{13}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SendMessageRequest) GetChatRoomID() int64 {
	if m != nil {
		return m.ChatRoomID
	}
	return 0
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{14}
}

func (m *SendMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageResponse.Unmarshal(m, b)
}
func (m *SendMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageResponse.Marshal(b, m, deterministic)
}
func (m *SendMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageResponse.Merge(m, src)
}
func (m *SendMessageResponse) XXX_Size() int {
	return xxx_messageInfo_SendMessageResponse.Size(m)
}
func (m *SendMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageResponse proto.InternalMessageInfo

type GetMessagesRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatRoomID           int64    `protobuf:"varint,2,opt,name=chatRoomID,proto3" json:"chatRoomID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{15}
}

func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(m, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetMessagesRequest) GetChatRoomID() int64 {
	if m != nil {
		return m.ChatRoomID
	}
	return 0
}

type GetMessagesResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{16}
}

func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(m, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	SenderID             int64    `protobuf:"varint,1,opt,name=senderID,proto3" json:"senderID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_52e5b35f0d7f0db1, []int{17}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSenderID() int64 {
	if m != nil {
		return m.SenderID
	}
	return 0
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "chatservice.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "chatservice.CreateUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "chatservice.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "chatservice.GetUserResponse")
	proto.RegisterType((*CreateChatRoomRequest)(nil), "chatservice.CreateChatRoomRequest")
	proto.RegisterType((*CreateChatRoomResponse)(nil), "chatservice.CreateChatRoomResponse")
	proto.RegisterType((*ListChatRoomsRequest)(nil), "chatservice.ListChatRoomsRequest")
	proto.RegisterType((*ListChatRoomsResponse)(nil), "chatservice.ListChatRoomsResponse")
	proto.RegisterType((*ListChatRoom)(nil), "chatservice.ListChatRoom")
	proto.RegisterType((*JoinChatRoomRequest)(nil), "chatservice.JoinChatRoomRequest")
	proto.RegisterType((*JoinChatRoomResponse)(nil), "chatservice.JoinChatRoomResponse")
	proto.RegisterType((*LeaveChatRoomRequest)(nil), "chatservice.LeaveChatRoomRequest")
	proto.RegisterType((*LeaveChatRoomResponse)(nil), "chatservice.LeaveChatRoomResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "chatservice.SendMessageRequest")
	proto.RegisterType((*SendMessageResponse)(nil), "chatservice.SendMessageResponse")
	proto.RegisterType((*GetMessagesRequest)(nil), "chatservice.GetMessagesRequest")
	proto.RegisterType((*GetMessagesResponse)(nil), "chatservice.GetMessagesResponse")
	proto.RegisterType((*Message)(nil), "chatservice.Message")
}

func init() { proto.RegisterFile("chatservice.proto", fileDescriptor_52e5b35f0d7f0db1) }

var fileDescriptor_52e5b35f0d7f0db1 = []byte{
	// 552 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x6d, 0xd3, 0x69, 0x6d, 0x4f, 0x4b, 0xd1, 0xbe, 0xfe, 0x50, 0x02, 0x1a, 0x9d, 0x11, 0xa2,
	0x17, 0xa8, 0x42, 0xe5, 0x02, 0xee, 0xb8, 0x18, 0xa2, 0x02, 0x75, 0x1b, 0xca, 0x34, 0x09, 0x09,
	0x71, 0x11, 0x5a, 0xd3, 0x05, 0xd1, 0x64, 0xc4, 0xd9, 0x78, 0x1c, 0x1e, 0x82, 0x27, 0xe1, 0x8d,
	0x50, 0x12, 0xc7, 0xb5, 0xd3, 0xb4, 0x43, 0x1a, 0xbb, 0xab, 0x3f, 0x1f, 0x9f, 0x73, 0xfc, 0xf5,
	0x3b, 0x0e, 0xf6, 0x66, 0xe7, 0x6e, 0x24, 0x78, 0x78, 0xe5, 0xcd, 0xf8, 0xe8, 0x22, 0x0c, 0xa2,
	0x80, 0x1a, 0x5a, 0x89, 0x3d, 0xc5, 0xde, 0x61, 0xc8, 0xdd, 0x88, 0x9f, 0x09, 0x1e, 0x3a, 0xfc,
	0xc7, 0x25, 0x17, 0x11, 0x11, 0x76, 0x7c, 0x77, 0xc9, 0xfb, 0xe5, 0x41, 0x79, 0x58, 0x77, 0x92,
	0xdf, 0xec, 0x19, 0x48, 0x07, 0x8a, 0x8b, 0xc0, 0x17, 0x9c, 0x7a, 0xd8, 0xbd, 0x14, 0x3c, 0x7c,
	0xf7, 0x26, 0xc1, 0x56, 0x1c, 0xb9, 0x62, 0x43, 0xb4, 0x26, 0x3c, 0xd2, 0x39, 0x37, 0x21, 0x9f,
	0xe0, 0xae, 0x42, 0x4a, 0xd2, 0x22, 0xf9, 0x53, 0x74, 0x53, 0xf9, 0xc3, 0x73, 0x37, 0x72, 0x82,
	0x60, 0x79, 0x0d, 0x2f, 0x31, 0x34, 0x67, 0x12, 0x7a, 0x1c, 0x93, 0x59, 0x09, 0x99, 0x51, 0x63,
	0xaf, 0xd0, 0xcb, 0x93, 0x4a, 0x0b, 0xfb, 0x40, 0x86, 0x54, 0xcc, 0x5a, 0x85, 0x8d, 0xd0, 0x99,
	0x7a, 0x22, 0xca, 0xce, 0x89, 0xeb, 0x6e, 0xf9, 0x01, 0xdd, 0x1c, 0x5e, 0x0a, 0xbd, 0x44, 0x3d,
	0xa6, 0x0d, 0xe3, 0x62, 0xbf, 0x3c, 0xa8, 0x0c, 0x1b, 0xe3, 0xfb, 0x23, 0xfd, 0x3f, 0xd3, 0x8f,
	0x39, 0x2b, 0x2c, 0x1b, 0xa3, 0xa9, 0x6f, 0x51, 0x0b, 0x96, 0x37, 0x97, 0xaa, 0x96, 0x37, 0x57,
	0x4d, 0xb4, 0xb4, 0x26, 0x1e, 0xa1, 0xfd, 0x3e, 0xf0, 0xfc, 0x7f, 0x6d, 0xa1, 0xd9, 0x04, 0x6b,
	0xad, 0x09, 0x3d, 0x74, 0x4c, 0xba, 0xf4, 0x4e, 0xec, 0x18, 0x9d, 0x29, 0x77, 0xaf, 0xf8, 0xff,
	0xd2, 0xb9, 0x87, 0x6e, 0x8e, 0x4f, 0x0a, 0x7d, 0x05, 0x9d, 0x72, 0x7f, 0x7e, 0xc4, 0x85, 0x70,
	0x17, 0xfc, 0x86, 0x32, 0xd4, 0x47, 0x75, 0x99, 0x32, 0xf5, 0x2b, 0x49, 0xd3, 0xb2, 0x25, 0xeb,
	0xa2, 0x6d, 0xe8, 0x48, 0xf9, 0x29, 0x68, 0xc2, 0x23, 0x59, 0x15, 0x37, 0xbd, 0xe5, 0x04, 0x6d,
	0x83, 0x4d, 0x0e, 0xc8, 0x73, 0xd4, 0xa4, 0x8d, 0x6c, 0x3e, 0x3a, 0xc6, 0x7c, 0x64, 0xa6, 0x14,
	0x8a, 0xbd, 0x46, 0x55, 0x16, 0xc9, 0x46, 0x4d, 0x70, 0x7f, 0xae, 0xb9, 0x51, 0x6b, 0xfd, 0xba,
	0x96, 0x71, 0xdd, 0xf1, 0xaf, 0x32, 0x76, 0xe2, 0x40, 0xd2, 0x09, 0x30, 0x53, 0x99, 0xa7, 0x7d,
	0x43, 0x77, 0xed, 0xd5, 0xb0, 0x1f, 0x6d, 0xdc, 0x97, 0xfd, 0x2a, 0xd1, 0x5b, 0x54, 0x17, 0x69,
	0xd8, 0xe9, 0x81, 0x81, 0x36, 0x1f, 0x0b, 0xfb, 0x61, 0xf1, 0x66, 0xc6, 0x33, 0xfe, 0x53, 0x41,
	0x4d, 0x4d, 0xfe, 0x27, 0xb4, 0x66, 0x46, 0x8a, 0x89, 0x15, 0x38, 0xc9, 0x0d, 0xa3, 0xfd, 0x78,
	0x2b, 0x46, 0x39, 0xfe, 0x88, 0x3b, 0xdf, 0xf5, 0xe0, 0xd2, 0xc1, 0xc6, 0x74, 0x66, 0x13, 0x60,
	0xb3, 0x6d, 0x10, 0xc5, 0xfc, 0x19, 0x14, 0x33, 0x9f, 0xfc, 0xf4, 0xf9, 0xfc, 0x16, 0xe8, 0xcf,
	0xd0, 0xfc, 0xa6, 0x85, 0x93, 0x06, 0xc6, 0xa9, 0x82, 0x67, 0xc0, 0x3e, 0xd8, 0x82, 0x30, 0xfa,
	0xa1, 0x67, 0x31, 0x6f, 0xb8, 0x20, 0xf7, 0x79, 0xc3, 0x85, 0x51, 0x2e, 0x8d, 0x7f, 0x97, 0x51,
	0x4f, 0xe7, 0xd6, 0xf3, 0x17, 0xe4, 0xa0, 0x21, 0x56, 0x91, 0x23, 0x73, 0xb6, 0xd6, 0x43, 0x6f,
	0x0f, 0x36, 0x03, 0x94, 0x77, 0x07, 0x8d, 0xc5, 0x2a, 0x61, 0x39, 0xce, 0xf5, 0x24, 0xe7, 0x38,
	0x0b, 0xc2, 0xc9, 0x4a, 0x5f, 0x76, 0x93, 0x6f, 0xea, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x6b, 0xca, 0xca, 0x24, 0x68, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/chatservice.User/createUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/chatservice.User/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.User/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatservice.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "getUser",
			Handler:    _User_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatservice.proto",
}

// ChatRoomClient is the client API for ChatRoom service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatRoomClient interface {
	CreateChatRoom(ctx context.Context, in *CreateChatRoomRequest, opts ...grpc.CallOption) (*CreateChatRoomResponse, error)
	ListChatRooms(ctx context.Context, in *ListChatRoomsRequest, opts ...grpc.CallOption) (*ListChatRoomsResponse, error)
	ListOwnedChatRooms(ctx context.Context, in *ListChatRoomsRequest, opts ...grpc.CallOption) (*ListChatRoomsResponse, error)
	JoinChatRoom(ctx context.Context, in *JoinChatRoomRequest, opts ...grpc.CallOption) (*JoinChatRoomResponse, error)
	LeaveChatRoom(ctx context.Context, in *LeaveChatRoomRequest, opts ...grpc.CallOption) (*LeaveChatRoomResponse, error)
}

type chatRoomClient struct {
	cc *grpc.ClientConn
}

func NewChatRoomClient(cc *grpc.ClientConn) ChatRoomClient {
	return &chatRoomClient{cc}
}

func (c *chatRoomClient) CreateChatRoom(ctx context.Context, in *CreateChatRoomRequest, opts ...grpc.CallOption) (*CreateChatRoomResponse, error) {
	out := new(CreateChatRoomResponse)
	err := c.cc.Invoke(ctx, "/chatservice.ChatRoom/createChatRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomClient) ListChatRooms(ctx context.Context, in *ListChatRoomsRequest, opts ...grpc.CallOption) (*ListChatRoomsResponse, error) {
	out := new(ListChatRoomsResponse)
	err := c.cc.Invoke(ctx, "/chatservice.ChatRoom/listChatRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomClient) ListOwnedChatRooms(ctx context.Context, in *ListChatRoomsRequest, opts ...grpc.CallOption) (*ListChatRoomsResponse, error) {
	out := new(ListChatRoomsResponse)
	err := c.cc.Invoke(ctx, "/chatservice.ChatRoom/listOwnedChatRooms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomClient) JoinChatRoom(ctx context.Context, in *JoinChatRoomRequest, opts ...grpc.CallOption) (*JoinChatRoomResponse, error) {
	out := new(JoinChatRoomResponse)
	err := c.cc.Invoke(ctx, "/chatservice.ChatRoom/joinChatRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatRoomClient) LeaveChatRoom(ctx context.Context, in *LeaveChatRoomRequest, opts ...grpc.CallOption) (*LeaveChatRoomResponse, error) {
	out := new(LeaveChatRoomResponse)
	err := c.cc.Invoke(ctx, "/chatservice.ChatRoom/leaveChatRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatRoomServer is the server API for ChatRoom service.
type ChatRoomServer interface {
	CreateChatRoom(context.Context, *CreateChatRoomRequest) (*CreateChatRoomResponse, error)
	ListChatRooms(context.Context, *ListChatRoomsRequest) (*ListChatRoomsResponse, error)
	ListOwnedChatRooms(context.Context, *ListChatRoomsRequest) (*ListChatRoomsResponse, error)
	JoinChatRoom(context.Context, *JoinChatRoomRequest) (*JoinChatRoomResponse, error)
	LeaveChatRoom(context.Context, *LeaveChatRoomRequest) (*LeaveChatRoomResponse, error)
}

// UnimplementedChatRoomServer can be embedded to have forward compatible implementations.
type UnimplementedChatRoomServer struct {
}

func (*UnimplementedChatRoomServer) CreateChatRoom(ctx context.Context, req *CreateChatRoomRequest) (*CreateChatRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChatRoom not implemented")
}
func (*UnimplementedChatRoomServer) ListChatRooms(ctx context.Context, req *ListChatRoomsRequest) (*ListChatRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatRooms not implemented")
}
func (*UnimplementedChatRoomServer) ListOwnedChatRooms(ctx context.Context, req *ListChatRoomsRequest) (*ListChatRoomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOwnedChatRooms not implemented")
}
func (*UnimplementedChatRoomServer) JoinChatRoom(ctx context.Context, req *JoinChatRoomRequest) (*JoinChatRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinChatRoom not implemented")
}
func (*UnimplementedChatRoomServer) LeaveChatRoom(ctx context.Context, req *LeaveChatRoomRequest) (*LeaveChatRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveChatRoom not implemented")
}

func RegisterChatRoomServer(s *grpc.Server, srv ChatRoomServer) {
	s.RegisterService(&_ChatRoom_serviceDesc, srv)
}

func _ChatRoom_CreateChatRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomServer).CreateChatRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatRoom/CreateChatRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomServer).CreateChatRoom(ctx, req.(*CreateChatRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRoom_ListChatRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomServer).ListChatRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatRoom/ListChatRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomServer).ListChatRooms(ctx, req.(*ListChatRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRoom_ListOwnedChatRooms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatRoomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomServer).ListOwnedChatRooms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatRoom/ListOwnedChatRooms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomServer).ListOwnedChatRooms(ctx, req.(*ListChatRoomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRoom_JoinChatRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinChatRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomServer).JoinChatRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatRoom/JoinChatRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomServer).JoinChatRoom(ctx, req.(*JoinChatRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatRoom_LeaveChatRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveChatRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatRoomServer).LeaveChatRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatRoom/LeaveChatRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatRoomServer).LeaveChatRoom(ctx, req.(*LeaveChatRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatRoom_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatservice.ChatRoom",
	HandlerType: (*ChatRoomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createChatRoom",
			Handler:    _ChatRoom_CreateChatRoom_Handler,
		},
		{
			MethodName: "listChatRooms",
			Handler:    _ChatRoom_ListChatRooms_Handler,
		},
		{
			MethodName: "listOwnedChatRooms",
			Handler:    _ChatRoom_ListOwnedChatRooms_Handler,
		},
		{
			MethodName: "joinChatRoom",
			Handler:    _ChatRoom_JoinChatRoom_Handler,
		},
		{
			MethodName: "leaveChatRoom",
			Handler:    _ChatRoom_LeaveChatRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatservice.proto",
}

// MessagingClient is the client API for Messaging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessagingClient interface {
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
}

type messagingClient struct {
	cc *grpc.ClientConn
}

func NewMessagingClient(cc *grpc.ClientConn) MessagingClient {
	return &messagingClient{cc}
}

func (c *messagingClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, "/chatservice.Messaging/sendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagingClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/chatservice.Messaging/getMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagingServer is the server API for Messaging service.
type MessagingServer interface {
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
}

// UnimplementedMessagingServer can be embedded to have forward compatible implementations.
type UnimplementedMessagingServer struct {
}

func (*UnimplementedMessagingServer) SendMessage(ctx context.Context, req *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedMessagingServer) GetMessages(ctx context.Context, req *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}

func RegisterMessagingServer(s *grpc.Server, srv MessagingServer) {
	s.RegisterService(&_Messaging_serviceDesc, srv)
}

func _Messaging_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.Messaging/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messaging_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagingServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.Messaging/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagingServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Messaging_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatservice.Messaging",
	HandlerType: (*MessagingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sendMessage",
			Handler:    _Messaging_SendMessage_Handler,
		},
		{
			MethodName: "getMessages",
			Handler:    _Messaging_GetMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatservice.proto",
}
